In [12]:
import numpy as np

A = np.array([[10,20],[30,40],[50,60]])

print('A shape = ', A.shape)
print(A)

print("A[0,0]==", A[0,0])
#행열 단위 출력
print("A[:,0]==", A[:,0])
#행 단위 출력
print("A[0:-1,1:2]==",A[0:-1,1:2])
#각 행열 단위에 맞는 모든 np 출력
print("A[:,:]==", A[:,:])
#모두 출력

A shape =  (3, 2)
[[10 20]
 [30 40]
 [50 60]]
A[0,0]== 10
A[:,0]== [10 30 50]
A[0:-1,1:2]== [[20]
 [40]]
A[:,:]== [[10 20]
 [30 40]
 [50 60]]
[[10 20]
 [30 40]
 [50 60]]


In [7]:
import numpy as np

arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr1.ndim)
print(arr1.shape)
print(np.sum(arr1, axis=0))
print(np.sum(arr1, axis=1))
print("")

print(np.exp(arr1))
print(np.log(arr1))

2
(3, 3)
[12 15 18]
[ 6 15 24]

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]
 [1.94591015 2.07944154 2.19722458]]
