In [2]:
import numpy as np

A = np.array([[10,20,30,40],[50,60,70,80]])
it = np.nditer(A,flags=['multi_index'],op_flags=['readwrite'])

while not it.finished:
    idx = it.multi_index
    print('index =>',idx,' value =>',A[idx])
    it.iternext()

index => (0, 0)  value => 10
index => (0, 1)  value => 20
index => (0, 2)  value => 30
index => (0, 3)  value => 40
index => (1, 0)  value => 50
index => (1, 1)  value => 60
index => (1, 2)  value => 70
index => (1, 3)  value => 80


In [6]:
import numpy as np

random_number1 = np.random.rand(3)
random_number2 = np.random.rand(1,3)
random_number3 = np.random.rand(3,1)

print("random_number1 ==", random_number1)
print("random_number2 ==", random_number2)
print("random_number3 ==", random_number3)

random_number1 == [0.56313958 0.1685692  0.50968914]
random_number2 == [[0.38536835 0.33208195 0.42416185]]
random_number3 == [[0.31148848]
 [0.50455499]
 [0.78317558]]


In [7]:
import numpy as np

A = np.array([2,6,3,1])

print("np.max(A) ==",np.max(A))
print("np.argmax(A) ==",np.argmax(A))

np.max(A) == 6
np.argmax(A) == 1


In [14]:
import numpy as np

loaded_data = np.loadtxt('./test.csv', delimiter=',', dtype=np.float32)

print('loaded_data.shpae = ',loaded_data.shape)
print(loaded_data)
print("orginal\n")
x_data = loaded_data[:,0:-1]
t_data = loaded_data[:,[-1]]
print("1,3 column print",x_data)
print("4 column print",t_data)


loaded_data.shpae =  (25, 4)
[[ 73.  80.  75. 152.]
 [ 93.  88.  93. 185.]
 [ 89.  91.  90. 180.]
 [ 96.  98. 100. 196.]
 [ 73.  66.  70. 142.]
 [ 53.  46.  55. 101.]
 [ 69.  74.  77. 149.]
 [ 47.  56.  60. 115.]
 [ 87.  79.  90. 175.]
 [ 79.  70.  88. 164.]
 [ 69.  70.  73. 141.]
 [ 70.  65.  74. 141.]
 [ 93.  95.  91. 184.]
 [ 79.  80.  73. 152.]
 [ 70.  73.  78. 148.]
 [ 93.  89.  96. 192.]
 [ 78.  75.  68. 147.]
 [ 81.  90.  93. 183.]
 [ 88.  92.  86. 177.]
 [ 78.  83.  77. 159.]
 [ 82.  86.  90. 177.]
 [ 86.  82.  89. 175.]
 [ 78.  83.  85. 175.]
 [ 76.  83.  71. 149.]
 [ 96.  93.  95. 192.]]
orginal

1,3 column print [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  8

In [12]:
import numpy as np

A = np.array([[10,20,30],[40,50,60]])

print(A.shape)
print('nomal\n')
row_add = np.array([70,80,90]).reshape(1,3)
column_add = np.array([1000,2000]).reshape(2,1)

B= np.concatenate((A,row_add),axis=0)
print(B)
print('add row\n')
C= np.concatenate((A,column_add),axis=1)
print(C)
print('add column\n')

(2, 3)
nomal

[[10 20 30]
 [40 50 60]
 [70 80 90]]
add row

[[  10   20   30 1000]
 [  40   50   60 2000]]
add column



In [15]:
import numpy as np

x = np.array([2,4,6,8])
print(np.sum(x))
print(np.exp(x))
print(np.log(x))

20
[   7.3890561    54.59815003  403.42879349 2980.95798704]
[0.69314718 1.38629436 1.79175947 2.07944154]


In [16]:
import numpy as np
A = np.ones([3,3])
print(A)

B = np.ones([3,2])
print(B)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [17]:
X= np.array([[2,4,6],[1,2,3],[0,5,8]])

print(np.max(X, axis=0))
print(np.min(X, axis=1))

print(np.argmax(X, axis=0))
print(np.argmin(X, axis=1))


[2 5 8]
[2 1 0]
[0 2 2]
[0 0 0]
