In [1]:
def square(x):
    return x*x

f = lambda x : x*x

x=10
ret1 = square(x)
print('ret1=',ret1)

ret2 = f(x)
print('ret2=',ret2)

ret1= 100
ret2= 100


## 람다 -> #define f(x) (x+100) 처리됨  

In [3]:
def print_hello():
    print("hello python")
    
def test_lambda(s,t):
    print("input1 ==",s,", input2 ==",t)

s=100
t=200

fx = lambda x, y : test_lambda(s,t)
fy = lambda x, y : print_hello()

fx(500,1000)
fy(300,600)

input1 == 100 , input2 == 200
hello python


In [24]:
class Person:
    
    count = 0
    
    
    
    def __init__(self,name,name2):
        self.name = name
        self.__name2 = name2
        #private member 변수
        
        print(self.name+" is initialized")
        
    def __printNames(self):
        print(self.name,self.__name2)
        #private method 함수
        
    def getNames(self):
        self.__printNames()
        #private method call
        return self.name, self.__name2
        
    def work(self,company):
        print(self.name+"is working in"+company)
    
    def sleep(self):
        print(self.name+" is sleeping")

    @classmethod
    def getCount(cls):
        return cls.count
    #클래스 메서드는 무조건 첫 arg로 class 나타내는 cls 변수 전달
    
    
# 클래스 변수 접근

print(Person.getCount())
#class method 접근

obj = Person("PARK","ji")
obj.work("ABCDEF")
obj.sleep()

#call private method to public method
print("\n",obj.getNames())
#print(obj._printNames())

0
PARK is initialized
PARKis working inABCDEF
PARK is sleeping
PARK ji

 ('PARK', 'ji')


## 파이썬 메서드의 첫번째 입력 파라메터로서 자기자신을 나타내는 self 반드시 써야함

In [1]:
import numpy as np

C = np.array([1,2,3])
print("C shape = ",C.shape)
print("C ndim = ",C.ndim)
#행렬화 전
C = C.reshape(1,3)
print("C shape = ",C.shape)
print("C ndim = ",C.ndim)
C = C.reshape(-1,3)
print("C shape = ",C.shape)
print("C ndim = ",C.ndim,"\n")

A = np.array([1,2,3,4,5,6])
print("A shape = ",A.shape)
print("A ndim = ",A.ndim)
print(A)
A= A.reshape(-1,3)
print("A shape = ",A.shape)
print("A ndim = ",A.ndim)
print(A,"\n\n")

A = np.array([[1,2],[3,4]])
print(A,"\n")

A=A/5
A=A*5 
#곱은 불가

print("broad cast")
print(A,"\n\n")

A = np.array([[1,2],[3,4],[5,6]])
B = A.T #전치행렬

print(A, A.ndim)
print("A행렬\n\n전치행렬로 변환\n",B.ndim)


A= np.array([[1,2,3],[4,5,6]])
B= np.array([[-1,-2],[-3,-4],[-5,-6]])

C= np.dot(A,B)
print("\nC shape :",C.shape)
print(C)

C shape =  (3,)
C ndim =  1
C shape =  (1, 3)
C ndim =  2
C shape =  (1, 3)
C ndim =  2 

A shape =  (6,)
A ndim =  1
[1 2 3 4 5 6]
A shape =  (2, 3)
A ndim =  2
[[1 2 3]
 [4 5 6]] 


[[1 2]
 [3 4]] 

broad cast
[[1. 2.]
 [3. 4.]] 


[[1 2]
 [3 4]
 [5 6]] 2
A행렬

전치행렬로 변환
 2

C shape : (2, 2)
[[-22 -28]
 [-49 -64]]


In [8]:
import numpy as np

A = np.array([1,2,3]).reshape(1,3)

B= np.array([1,2,3]).reshape(1,3)
B=B.T

print(A.shape)
print(B.shape)

C= A+B
print("\n")
print(C)
print("\n")

D = A*B
print(D)
print("\n")

A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([2,4,6]).reshape(-1,3)

print(A+B)
print()
A = np.array([1,2,3,4]).reshape(-1,1)
B = np.array([2,4,6,8]).reshape(-1,4)
print(A+B)

(1, 3)
(3, 1)


[[2 3 4]
 [3 4 5]
 [4 5 6]]


[[1 2 3]
 [2 4 6]
 [3 6 9]]


[[ 3  6  9]
 [ 6  9 12]
 [ 9 12 15]]

[[ 3  5  7  9]
 [ 4  6  8 10]
 [ 5  7  9 11]
 [ 6  8 10 12]]


In [48]:
A = np.array([[10,20],[30,40],[50,60]])
print(A.shape)
print("\n")
print(A[:,:])
print(A[0,0])
print(A[2,1])
print(A[:,0])
print(A[:,1])
print(A[:-1,1])


(3, 2)


[[10 20]
 [30 40]
 [50 60]]
10
60
[10 30 50]
[20 40 60]
[20 40]


In [50]:
import numpy as np
A = np.array([[10,20,30,40],[50,60,70,80]])

it = np.nditer(A, flags=["multi_index"],op_flags=['readwrite'])

while not it.finished:
    idx= it.multi_index
    print("index = ",idx,"values = ",A[idx])
    it.iternext()

index =  (0, 0) values =  10
index =  (0, 1) values =  20
index =  (0, 2) values =  30
index =  (0, 3) values =  40
index =  (1, 0) values =  50
index =  (1, 1) values =  60
index =  (1, 2) values =  70
index =  (1, 3) values =  80


In [53]:
number1 = np.random.rand(1,3)
number2 = np.random.rand(3,4)
print(number1)
print(number2)
number3= np.ones([1,3])
number4 = np.zeros([1,3])
print(number3)
print(number4)

[[0.35257173 0.92764775 0.58889007]]
[[0.66538788 0.71994785 0.34050139 0.98323225]
 [0.78055096 0.26735261 0.90144055 0.44195981]
 [0.64336021 0.19413862 0.90584588 0.33754625]]
[[1. 1. 1.]]
[[0. 0. 0.]]


In [64]:
import numpy as np

load_data = np.loadtxt('./test.csv', delimiter=',',dtype=np.float32)

x_data = load_data[:,0:-1]
t_data = load_data[:,[-1]]
print(x_data.ndim,x_data.shape)
print(t_data.ndim,t_data.shape)

2 (25, 3)
2 (25, 1)


In [70]:
A = np.array([[10,20,30],[40,50,60]])
row_add = np.array([70,80,90]).reshape(1,3)
A = np.concatenate((A,row_add),axis=0)
print(A)
print()


B = np.array([[10,20],[30,40]])
col_add = np.array([50,60]).reshape(-1,1)
B = np.concatenate((B,col_add),axis=1)
print(B)

[[10 20 30]
 [40 50 60]
 [70 80 90]]

[[10 20 50]
 [30 40 60]]


In [71]:
A= np.array([[2,4,6],[1,2,3],[0,5,8]])

print(np.max(A,axis=0))
print(np.min(A,axis=0))
print(np.max(A,axis=1))

[2 5 8]
[0 2 3]
[6 3 8]
